// Mirrors https://api.jquery.com/category/events/ on/off/one/trigger; divergences inherited from divergence.md: no bubbling, capture, delegation, DOM bridge, or bound this.
import { describe, expect, it, vi } from 'vitest'
import pdfquery, { PdfEvent } from '../../index.js'
describe('events', () => {
  it('on and trigger deliver PdfEvent to every node', () => { const nodes = [{ id: 'a' }, { id: 'b' }], seen: PdfEvent<{ id: string }, { score: number }>[] = []; pdfquery<{ id: string }, { verify: { score: number } }>(nodes).on('verify', (event) => seen.push(event)).trigger('verify', { score: 1 }); expect(seen).toEqual([{ type: 'verify', target: nodes[0], detail: { score: 1 } }, { type: 'verify', target: nodes[1], detail: { score: 1 } }]) })
  it('invokes handlers in insertion order', () => { const order: number[] = [], $ = pdfquery({ id: 'a' }); $.on('change', () => order.push(1)); $.on('change', () => order.push(2)); $.trigger('change'); expect(order).toEqual([1, 2]) })
  it('deduplicates repeated type and handler registrations', () => { const handler = vi.fn(); pdfquery({ id: 'a' }).on('change', handler).on('change', handler).trigger('change'); expect(handler).toHaveBeenCalledTimes(1) })
  it('one removes itself after the first trigger', () => { const handler = vi.fn(), $ = pdfquery({ id: 'a' }); $.one('load', handler).trigger('load').trigger('load'); expect(handler).toHaveBeenCalledTimes(1) })
  it('off(type, handler) removes one specific handler', () => { const keep = vi.fn(), remove = vi.fn(), $ = pdfquery({ id: 'a' }); $.on('change', keep).on('change', remove).off('change', remove).trigger('change'); expect(keep).toHaveBeenCalledTimes(1); expect(remove).not.toHaveBeenCalled() })
  it('off(type, handler) removes one-shot handlers by original handler', () => { const handler = vi.fn(), $ = pdfquery({ id: 'a' }); $.one('change', handler).off('change', handler).trigger('change'); expect(handler).not.toHaveBeenCalled() })
  it('off(type) removes all handlers for that type only', () => { const change = vi.fn(), verify = vi.fn(), $ = pdfquery({ id: 'a' }); $.on('change', change).on('verify', verify).off('change').trigger('change').trigger('verify'); expect(change).not.toHaveBeenCalled(); expect(verify).toHaveBeenCalledTimes(1) })
  it('off() removes every handler from the collection nodes', () => { const change = vi.fn(), verify = vi.fn(), $ = pdfquery({ id: 'a' }); $.on('change', change).on('verify', verify).off().trigger('change').trigger('verify'); expect(change).not.toHaveBeenCalled(); expect(verify).not.toHaveBeenCalled() })
  it('continues handlers and rethrows when no error listener exists', () => { const error = new Error('boom'), after = vi.fn(), $ = pdfquery({ id: 'a' }); $.on('change', () => { throw error }); $.on('change', after); expect(() => $.trigger('change')).toThrow(error); expect(after).toHaveBeenCalledTimes(1) })
  it('swallows handler errors and emits error detail when an error listener exists', () => { const node = { id: 'a' }, error = new Error('boom'), emitted: unknown[] = [], after = vi.fn(), $ = pdfquery(node); $.on('error', (event) => emitted.push(event.detail)); $.on('change', () => { throw error }); $.on('change', after); expect(() => $.trigger('change')).not.toThrow(); expect(after).toHaveBeenCalledTimes(1); expect(emitted).toEqual([{ source: 'handler', type: 'change', error }]) })
  it('deduplicates repeated nodes during trigger', () => { const node = { id: 'a' }, handler = vi.fn(); pdfquery([node, node]).on('change', handler).trigger('change'); expect(handler).toHaveBeenCalledTimes(1) })
})
